package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * Account generated by hbm2java
 */
public class Account implements java.io.Serializable {

	private int id;
	private Role role;
	private String username;
	private String password;
	private String fullName;
	private String address;
	private String email;
	private String phone;
	private Boolean status;

	public Account() {
	}

	public Account(int id) {
		this.id = id;
	}

	public Account(int id, Role role, String username, String password, String fullName, String address, String email,
			String phone, Boolean status) {
		this.id = id;
		this.role = role;
		this.username = username;
		this.password = password;
		this.fullName = fullName;
		this.address = address;
		this.email = email;
		this.phone = phone;
		this.status = status;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Boolean getStatus() {
		return this.status;
	}

	public void setStatus(Boolean status) {
		this.status = status;
	}

}
