package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * Alien generated by hbm2java
 */
public class Alien implements java.io.Serializable {

	private int aid;
	private String aname;
	private String color;

	public Alien() {
	}

	public Alien(int aid) {
		this.aid = aid;
	}

	public Alien(int aid, String aname, String color) {
		this.aid = aid;
		this.aname = aname;
		this.color = color;
	}

	public int getAid() {
		return this.aid;
	}

	public void setAid(int aid) {
		this.aid = aid;
	}

	public String getAname() {
		return this.aname;
	}

	public void setAname(String aname) {
		this.aname = aname;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

}
