package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * HostSummaryByStatementLatency generated by hbm2java
 */
public class HostSummaryByStatementLatency implements java.io.Serializable {

	private HostSummaryByStatementLatencyId id;

	public HostSummaryByStatementLatency() {
	}

	public HostSummaryByStatementLatency(HostSummaryByStatementLatencyId id) {
		this.id = id;
	}

	public HostSummaryByStatementLatencyId getId() {
		return this.id;
	}

	public void setId(HostSummaryByStatementLatencyId id) {
		this.id = id;
	}

}
