package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * HostSummaryByStatementType generated by hbm2java
 */
public class HostSummaryByStatementType implements java.io.Serializable {

	private HostSummaryByStatementTypeId id;

	public HostSummaryByStatementType() {
	}

	public HostSummaryByStatementType(HostSummaryByStatementTypeId id) {
		this.id = id;
	}

	public HostSummaryByStatementTypeId getId() {
		return this.id;
	}

	public void setId(HostSummaryByStatementTypeId id) {
		this.id = id;
	}

}
