package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * HostSummary generated by hbm2java
 */
public class HostSummary implements java.io.Serializable {

	private HostSummaryId id;

	public HostSummary() {
	}

	public HostSummary(HostSummaryId id) {
		this.id = id;
	}

	public HostSummaryId getId() {
		return this.id;
	}

	public void setId(HostSummaryId id) {
		this.id = id;
	}

}
