package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * HostSummaryByFileIo generated by hbm2java
 */
public class HostSummaryByFileIo implements java.io.Serializable {

	private HostSummaryByFileIoId id;

	public HostSummaryByFileIo() {
	}

	public HostSummaryByFileIo(HostSummaryByFileIoId id) {
		this.id = id;
	}

	public HostSummaryByFileIoId getId() {
		return this.id;
	}

	public void setId(HostSummaryByFileIoId id) {
		this.id = id;
	}

}
