package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * InnodbLockWaits generated by hbm2java
 */
public class InnodbLockWaits implements java.io.Serializable {

	private InnodbLockWaitsId id;

	public InnodbLockWaits() {
	}

	public InnodbLockWaits(InnodbLockWaitsId id) {
		this.id = id;
	}

	public InnodbLockWaitsId getId() {
		return this.id;
	}

	public void setId(InnodbLockWaitsId id) {
		this.id = id;
	}

}
