package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * IoByThreadByLatency generated by hbm2java
 */
public class IoByThreadByLatency implements java.io.Serializable {

	private IoByThreadByLatencyId id;

	public IoByThreadByLatency() {
	}

	public IoByThreadByLatency(IoByThreadByLatencyId id) {
		this.id = id;
	}

	public IoByThreadByLatencyId getId() {
		return this.id;
	}

	public void setId(IoByThreadByLatencyId id) {
		this.id = id;
	}

}
