package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * IoGlobalByWaitByBytes generated by hbm2java
 */
public class IoGlobalByWaitByBytes implements java.io.Serializable {

	private IoGlobalByWaitByBytesId id;

	public IoGlobalByWaitByBytes() {
	}

	public IoGlobalByWaitByBytes(IoGlobalByWaitByBytesId id) {
		this.id = id;
	}

	public IoGlobalByWaitByBytesId getId() {
		return this.id;
	}

	public void setId(IoGlobalByWaitByBytesId id) {
		this.id = id;
	}

}
