package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * IoGlobalByFileByLatency generated by hbm2java
 */
public class IoGlobalByFileByLatency implements java.io.Serializable {

	private IoGlobalByFileByLatencyId id;

	public IoGlobalByFileByLatency() {
	}

	public IoGlobalByFileByLatency(IoGlobalByFileByLatencyId id) {
		this.id = id;
	}

	public IoGlobalByFileByLatencyId getId() {
		return this.id;
	}

	public void setId(IoGlobalByFileByLatencyId id) {
		this.id = id;
	}

}
