package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * IoGlobalByWaitByLatency generated by hbm2java
 */
public class IoGlobalByWaitByLatency implements java.io.Serializable {

	private IoGlobalByWaitByLatencyId id;

	public IoGlobalByWaitByLatency() {
	}

	public IoGlobalByWaitByLatency(IoGlobalByWaitByLatencyId id) {
		this.id = id;
	}

	public IoGlobalByWaitByLatencyId getId() {
		return this.id;
	}

	public void setId(IoGlobalByWaitByLatencyId id) {
		this.id = id;
	}

}
