package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * MemoryByHostByCurrentBytes generated by hbm2java
 */
public class MemoryByHostByCurrentBytes implements java.io.Serializable {

	private MemoryByHostByCurrentBytesId id;

	public MemoryByHostByCurrentBytes() {
	}

	public MemoryByHostByCurrentBytes(MemoryByHostByCurrentBytesId id) {
		this.id = id;
	}

	public MemoryByHostByCurrentBytesId getId() {
		return this.id;
	}

	public void setId(MemoryByHostByCurrentBytesId id) {
		this.id = id;
	}

}
