package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * MemoryGlobalByCurrentBytes generated by hbm2java
 */
public class MemoryGlobalByCurrentBytes implements java.io.Serializable {

	private MemoryGlobalByCurrentBytesId id;

	public MemoryGlobalByCurrentBytes() {
	}

	public MemoryGlobalByCurrentBytes(MemoryGlobalByCurrentBytesId id) {
		this.id = id;
	}

	public MemoryGlobalByCurrentBytesId getId() {
		return this.id;
	}

	public void setId(MemoryGlobalByCurrentBytesId id) {
		this.id = id;
	}

}
