package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * MemoryByThreadByCurrentBytes generated by hbm2java
 */
public class MemoryByThreadByCurrentBytes implements java.io.Serializable {

	private MemoryByThreadByCurrentBytesId id;

	public MemoryByThreadByCurrentBytes() {
	}

	public MemoryByThreadByCurrentBytes(MemoryByThreadByCurrentBytesId id) {
		this.id = id;
	}

	public MemoryByThreadByCurrentBytesId getId() {
		return this.id;
	}

	public void setId(MemoryByThreadByCurrentBytesId id) {
		this.id = id;
	}

}
