package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * MemoryByUserByCurrentBytes generated by hbm2java
 */
public class MemoryByUserByCurrentBytes implements java.io.Serializable {

	private MemoryByUserByCurrentBytesId id;

	public MemoryByUserByCurrentBytes() {
	}

	public MemoryByUserByCurrentBytes(MemoryByUserByCurrentBytesId id) {
		this.id = id;
	}

	public MemoryByUserByCurrentBytesId getId() {
		return this.id;
	}

	public void setId(MemoryByUserByCurrentBytesId id) {
		this.id = id;
	}

}
