package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * Metrics generated by hbm2java
 */
public class Metrics implements java.io.Serializable {

	private MetricsId id;

	public Metrics() {
	}

	public Metrics(MetricsId id) {
		this.id = id;
	}

	public MetricsId getId() {
		return this.id;
	}

	public void setId(MetricsId id) {
		this.id = id;
	}

}
