package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * Photo generated by hbm2java
 */
public class Photo implements java.io.Serializable {

	private Integer id;
	private Product product;
	private String name;
	private Byte status;
	private Byte main;

	public Photo() {
	}

	public Photo(Product product, String name, Byte status, Byte main) {
		this.product = product;
		this.name = name;
		this.status = status;
		this.main = main;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	public Byte getMain() {
		return this.main;
	}

	public void setMain(Byte main) {
		this.main = main;
	}

}
