package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * PsCheckLostInstrumentation generated by hbm2java
 */
public class PsCheckLostInstrumentation implements java.io.Serializable {

	private PsCheckLostInstrumentationId id;

	public PsCheckLostInstrumentation() {
	}

	public PsCheckLostInstrumentation(PsCheckLostInstrumentationId id) {
		this.id = id;
	}

	public PsCheckLostInstrumentationId getId() {
		return this.id;
	}

	public void setId(PsCheckLostInstrumentationId id) {
		this.id = id;
	}

}
