package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class Role implements java.io.Serializable {

	private int id;
	private String name;
	private Set accounts = new HashSet(0);
	private Set accounts_1 = new HashSet(0);

	public Role() {
	}

	public Role(int id) {
		this.id = id;
	}

	public Role(int id, String name, Set accounts, Set accounts_1) {
		this.id = id;
		this.name = name;
		this.accounts = accounts;
		this.accounts_1 = accounts_1;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Set getAccounts() {
		return this.accounts;
	}

	public void setAccounts(Set accounts) {
		this.accounts = accounts;
	}

	public Set getAccounts_1() {
		return this.accounts_1;
	}

	public void setAccounts_1(Set accounts_1) {
		this.accounts_1 = accounts_1;
	}

}
