package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * SchemaTableStatisticsWithBuffer generated by hbm2java
 */
public class SchemaTableStatisticsWithBuffer implements java.io.Serializable {

	private SchemaTableStatisticsWithBufferId id;

	public SchemaTableStatisticsWithBuffer() {
	}

	public SchemaTableStatisticsWithBuffer(SchemaTableStatisticsWithBufferId id) {
		this.id = id;
	}

	public SchemaTableStatisticsWithBufferId getId() {
		return this.id;
	}

	public void setId(SchemaTableStatisticsWithBufferId id) {
		this.id = id;
	}

}
