package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * SchemaIndexStatistics generated by hbm2java
 */
public class SchemaIndexStatistics implements java.io.Serializable {

	private SchemaIndexStatisticsId id;

	public SchemaIndexStatistics() {
	}

	public SchemaIndexStatistics(SchemaIndexStatisticsId id) {
		this.id = id;
	}

	public SchemaIndexStatisticsId getId() {
		return this.id;
	}

	public void setId(SchemaIndexStatisticsId id) {
		this.id = id;
	}

}
