package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * SchemaTableLockWaits generated by hbm2java
 */
public class SchemaTableLockWaits implements java.io.Serializable {

	private SchemaTableLockWaitsId id;

	public SchemaTableLockWaits() {
	}

	public SchemaTableLockWaits(SchemaTableLockWaitsId id) {
		this.id = id;
	}

	public SchemaTableLockWaitsId getId() {
		return this.id;
	}

	public void setId(SchemaTableLockWaitsId id) {
		this.id = id;
	}

}
