package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * SchemaAutoIncrementColumns generated by hbm2java
 */
public class SchemaAutoIncrementColumns implements java.io.Serializable {

	private SchemaAutoIncrementColumnsId id;

	public SchemaAutoIncrementColumns() {
	}

	public SchemaAutoIncrementColumns(SchemaAutoIncrementColumnsId id) {
		this.id = id;
	}

	public SchemaAutoIncrementColumnsId getId() {
		return this.id;
	}

	public void setId(SchemaAutoIncrementColumnsId id) {
		this.id = id;
	}

}
