package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * SchemaRedundantIndexes generated by hbm2java
 */
public class SchemaRedundantIndexes implements java.io.Serializable {

	private SchemaRedundantIndexesId id;

	public SchemaRedundantIndexes() {
	}

	public SchemaRedundantIndexes(SchemaRedundantIndexesId id) {
		this.id = id;
	}

	public SchemaRedundantIndexesId getId() {
		return this.id;
	}

	public void setId(SchemaRedundantIndexesId id) {
		this.id = id;
	}

}
