package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * SessionSslStatus generated by hbm2java
 */
public class SessionSslStatus implements java.io.Serializable {

	private SessionSslStatusId id;

	public SessionSslStatus() {
	}

	public SessionSslStatus(SessionSslStatusId id) {
		this.id = id;
	}

	public SessionSslStatusId getId() {
		return this.id;
	}

	public void setId(SessionSslStatusId id) {
		this.id = id;
	}

}
