package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * Session generated by hbm2java
 */
public class Session implements java.io.Serializable {

	private SessionId id;

	public Session() {
	}

	public Session(SessionId id) {
		this.id = id;
	}

	public SessionId getId() {
		return this.id;
	}

	public void setId(SessionId id) {
		this.id = id;
	}

}
