package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * StatementsWithErrorsOrWarnings generated by hbm2java
 */
public class StatementsWithErrorsOrWarnings implements java.io.Serializable {

	private StatementsWithErrorsOrWarningsId id;

	public StatementsWithErrorsOrWarnings() {
	}

	public StatementsWithErrorsOrWarnings(StatementsWithErrorsOrWarningsId id) {
		this.id = id;
	}

	public StatementsWithErrorsOrWarningsId getId() {
		return this.id;
	}

	public void setId(StatementsWithErrorsOrWarningsId id) {
		this.id = id;
	}

}
