package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * StatementsWithSorting generated by hbm2java
 */
public class StatementsWithSorting implements java.io.Serializable {

	private StatementsWithSortingId id;

	public StatementsWithSorting() {
	}

	public StatementsWithSorting(StatementsWithSortingId id) {
		this.id = id;
	}

	public StatementsWithSortingId getId() {
		return this.id;
	}

	public void setId(StatementsWithSortingId id) {
		this.id = id;
	}

}
