package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * StatementsWithRuntimesIn95thPercentile generated by hbm2java
 */
public class StatementsWithRuntimesIn95thPercentile implements java.io.Serializable {

	private StatementsWithRuntimesIn95thPercentileId id;

	public StatementsWithRuntimesIn95thPercentile() {
	}

	public StatementsWithRuntimesIn95thPercentile(StatementsWithRuntimesIn95thPercentileId id) {
		this.id = id;
	}

	public StatementsWithRuntimesIn95thPercentileId getId() {
		return this.id;
	}

	public void setId(StatementsWithRuntimesIn95thPercentileId id) {
		this.id = id;
	}

}
