package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * StatementsWithFullTableScans generated by hbm2java
 */
public class StatementsWithFullTableScans implements java.io.Serializable {

	private StatementsWithFullTableScansId id;

	public StatementsWithFullTableScans() {
	}

	public StatementsWithFullTableScans(StatementsWithFullTableScansId id) {
		this.id = id;
	}

	public StatementsWithFullTableScansId getId() {
		return this.id;
	}

	public void setId(StatementsWithFullTableScansId id) {
		this.id = id;
	}

}
