package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class Student implements java.io.Serializable {

	private int rollno;
	private int marks;
	private String sname;
	private Set laptops = new HashSet(0);

	public Student() {
	}

	public Student(int rollno, int marks) {
		this.rollno = rollno;
		this.marks = marks;
	}

	public Student(int rollno, int marks, String sname, Set laptops) {
		this.rollno = rollno;
		this.marks = marks;
		this.sname = sname;
		this.laptops = laptops;
	}

	public int getRollno() {
		return this.rollno;
	}

	public void setRollno(int rollno) {
		this.rollno = rollno;
	}

	public int getMarks() {
		return this.marks;
	}

	public void setMarks(int marks) {
		this.marks = marks;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public Set getLaptops() {
		return this.laptops;
	}

	public void setLaptops(Set laptops) {
		this.laptops = laptops;
	}

}
