package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * UserSummaryByStages generated by hbm2java
 */
public class UserSummaryByStages implements java.io.Serializable {

	private UserSummaryByStagesId id;

	public UserSummaryByStages() {
	}

	public UserSummaryByStages(UserSummaryByStagesId id) {
		this.id = id;
	}

	public UserSummaryByStagesId getId() {
		return this.id;
	}

	public void setId(UserSummaryByStagesId id) {
		this.id = id;
	}

}
