package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * UserSummaryByStatementLatency generated by hbm2java
 */
public class UserSummaryByStatementLatency implements java.io.Serializable {

	private UserSummaryByStatementLatencyId id;

	public UserSummaryByStatementLatency() {
	}

	public UserSummaryByStatementLatency(UserSummaryByStatementLatencyId id) {
		this.id = id;
	}

	public UserSummaryByStatementLatencyId getId() {
		return this.id;
	}

	public void setId(UserSummaryByStatementLatencyId id) {
		this.id = id;
	}

}
