package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * WaitClassesGlobalByLatency generated by hbm2java
 */
public class WaitClassesGlobalByLatency implements java.io.Serializable {

	private WaitClassesGlobalByLatencyId id;

	public WaitClassesGlobalByLatency() {
	}

	public WaitClassesGlobalByLatency(WaitClassesGlobalByLatencyId id) {
		this.id = id;
	}

	public WaitClassesGlobalByLatencyId getId() {
		return this.id;
	}

	public void setId(WaitClassesGlobalByLatencyId id) {
		this.id = id;
	}

}
