package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final

/**
 * WaitClassesGlobalByAvgLatency generated by hbm2java
 */
public class WaitClassesGlobalByAvgLatency implements java.io.Serializable {

	private WaitClassesGlobalByAvgLatencyId id;

	public WaitClassesGlobalByAvgLatency() {
	}

	public WaitClassesGlobalByAvgLatency(WaitClassesGlobalByAvgLatencyId id) {
		this.id = id;
	}

	public WaitClassesGlobalByAvgLatencyId getId() {
		return this.id;
	}

	public void setId(WaitClassesGlobalByAvgLatencyId id) {
		this.id = id;
	}

}
