package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.hostSummaryByFileIoId;

/**
 * X.hostSummaryByFileIo generated by hbm2java
 */
public class X.hostSummaryByFileIo  implements java.io.Serializable {


     private X.hostSummaryByFileIoId id;

    public X.hostSummaryByFileIo() {
    }

    public X.hostSummaryByFileIo(X.hostSummaryByFileIoId id) {
       this.id = id;
    }
   
    public X.hostSummaryByFileIoId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByFileIoId id) {
        this.id = id;
    }




}


