package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.hostSummaryByStatementLatencyId;

/**
 * X.hostSummaryByStatementLatency generated by hbm2java
 */
public class X.hostSummaryByStatementLatency  implements java.io.Serializable {


     private X.hostSummaryByStatementLatencyId id;

    public X.hostSummaryByStatementLatency() {
    }

    public X.hostSummaryByStatementLatency(X.hostSummaryByStatementLatencyId id) {
       this.id = id;
    }
   
    public X.hostSummaryByStatementLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByStatementLatencyId id) {
        this.id = id;
    }




}


