package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.hostSummaryByStagesId;

/**
 * X.hostSummaryByStages generated by hbm2java
 */
public class X.hostSummaryByStages  implements java.io.Serializable {


     private X.hostSummaryByStagesId id;

    public X.hostSummaryByStages() {
    }

    public X.hostSummaryByStages(X.hostSummaryByStagesId id) {
       this.id = id;
    }
   
    public X.hostSummaryByStagesId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByStagesId id) {
        this.id = id;
    }




}


