package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.hostSummaryId;

/**
 * X.hostSummary generated by hbm2java
 */
public class X.hostSummary  implements java.io.Serializable {


     private X.hostSummaryId id;

    public X.hostSummary() {
    }

    public X.hostSummary(X.hostSummaryId id) {
       this.id = id;
    }
   
    public X.hostSummaryId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryId id) {
        this.id = id;
    }




}


