package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.hostSummaryByFileIoTypeId;

/**
 * X.hostSummaryByFileIoType generated by hbm2java
 */
public class X.hostSummaryByFileIoType  implements java.io.Serializable {


     private X.hostSummaryByFileIoTypeId id;

    public X.hostSummaryByFileIoType() {
    }

    public X.hostSummaryByFileIoType(X.hostSummaryByFileIoTypeId id) {
       this.id = id;
    }
   
    public X.hostSummaryByFileIoTypeId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByFileIoTypeId id) {
        this.id = id;
    }




}


