package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.hostSummaryByStatementTypeId;

/**
 * X.hostSummaryByStatementType generated by hbm2java
 */
public class X.hostSummaryByStatementType  implements java.io.Serializable {


     private X.hostSummaryByStatementTypeId id;

    public X.hostSummaryByStatementType() {
    }

    public X.hostSummaryByStatementType(X.hostSummaryByStatementTypeId id) {
       this.id = id;
    }
   
    public X.hostSummaryByStatementTypeId getId() {
        return this.id;
    }
    
    public void setId(X.hostSummaryByStatementTypeId id) {
        this.id = id;
    }




}


