package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.innodbLockWaitsId;

/**
 * X.innodbLockWaits generated by hbm2java
 */
public class X.innodbLockWaits  implements java.io.Serializable {


     private X.innodbLockWaitsId id;

    public X.innodbLockWaits() {
    }

    public X.innodbLockWaits(X.innodbLockWaitsId id) {
       this.id = id;
    }
   
    public X.innodbLockWaitsId getId() {
        return this.id;
    }
    
    public void setId(X.innodbLockWaitsId id) {
        this.id = id;
    }




}


