package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.innodbBufferStatsByTableId;

/**
 * X.innodbBufferStatsByTable generated by hbm2java
 */
public class X.innodbBufferStatsByTable  implements java.io.Serializable {


     private X.innodbBufferStatsByTableId id;

    public X.innodbBufferStatsByTable() {
    }

    public X.innodbBufferStatsByTable(X.innodbBufferStatsByTableId id) {
       this.id = id;
    }
   
    public X.innodbBufferStatsByTableId getId() {
        return this.id;
    }
    
    public void setId(X.innodbBufferStatsByTableId id) {
        this.id = id;
    }




}


