package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.innodbBufferStatsBySchemaId;

/**
 * X.innodbBufferStatsBySchema generated by hbm2java
 */
public class X.innodbBufferStatsBySchema  implements java.io.Serializable {


     private X.innodbBufferStatsBySchemaId id;

    public X.innodbBufferStatsBySchema() {
    }

    public X.innodbBufferStatsBySchema(X.innodbBufferStatsBySchemaId id) {
       this.id = id;
    }
   
    public X.innodbBufferStatsBySchemaId getId() {
        return this.id;
    }
    
    public void setId(X.innodbBufferStatsBySchemaId id) {
        this.id = id;
    }




}


