package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.ioGlobalByWaitByBytesId;

/**
 * X.ioGlobalByWaitByBytes generated by hbm2java
 */
public class X.ioGlobalByWaitByBytes  implements java.io.Serializable {


     private X.ioGlobalByWaitByBytesId id;

    public X.ioGlobalByWaitByBytes() {
    }

    public X.ioGlobalByWaitByBytes(X.ioGlobalByWaitByBytesId id) {
       this.id = id;
    }
   
    public X.ioGlobalByWaitByBytesId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByWaitByBytesId id) {
        this.id = id;
    }




}


