package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.ioByThreadByLatencyId;

/**
 * X.ioByThreadByLatency generated by hbm2java
 */
public class X.ioByThreadByLatency  implements java.io.Serializable {


     private X.ioByThreadByLatencyId id;

    public X.ioByThreadByLatency() {
    }

    public X.ioByThreadByLatency(X.ioByThreadByLatencyId id) {
       this.id = id;
    }
   
    public X.ioByThreadByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.ioByThreadByLatencyId id) {
        this.id = id;
    }




}


