package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.ioGlobalByFileByBytesId;

/**
 * X.ioGlobalByFileByBytes generated by hbm2java
 */
public class X.ioGlobalByFileByBytes  implements java.io.Serializable {


     private X.ioGlobalByFileByBytesId id;

    public X.ioGlobalByFileByBytes() {
    }

    public X.ioGlobalByFileByBytes(X.ioGlobalByFileByBytesId id) {
       this.id = id;
    }
   
    public X.ioGlobalByFileByBytesId getId() {
        return this.id;
    }
    
    public void setId(X.ioGlobalByFileByBytesId id) {
        this.id = id;
    }




}


