package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.latestFileIoId;

/**
 * X.latestFileIo generated by hbm2java
 */
public class X.latestFileIo  implements java.io.Serializable {


     private X.latestFileIoId id;

    public X.latestFileIo() {
    }

    public X.latestFileIo(X.latestFileIoId id) {
       this.id = id;
    }
   
    public X.latestFileIoId getId() {
        return this.id;
    }
    
    public void setId(X.latestFileIoId id) {
        this.id = id;
    }




}


