package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.memoryByThreadByCurrentBytesId;

/**
 * X.memoryByThreadByCurrentBytes generated by hbm2java
 */
public class X.memoryByThreadByCurrentBytes  implements java.io.Serializable {


     private X.memoryByThreadByCurrentBytesId id;

    public X.memoryByThreadByCurrentBytes() {
    }

    public X.memoryByThreadByCurrentBytes(X.memoryByThreadByCurrentBytesId id) {
       this.id = id;
    }
   
    public X.memoryByThreadByCurrentBytesId getId() {
        return this.id;
    }
    
    public void setId(X.memoryByThreadByCurrentBytesId id) {
        this.id = id;
    }




}


