package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.psDigestAvgLatencyDistributionId;

/**
 * X.psDigestAvgLatencyDistribution generated by hbm2java
 */
public class X.psDigestAvgLatencyDistribution  implements java.io.Serializable {


     private X.psDigestAvgLatencyDistributionId id;

    public X.psDigestAvgLatencyDistribution() {
    }

    public X.psDigestAvgLatencyDistribution(X.psDigestAvgLatencyDistributionId id) {
       this.id = id;
    }
   
    public X.psDigestAvgLatencyDistributionId getId() {
        return this.id;
    }
    
    public void setId(X.psDigestAvgLatencyDistributionId id) {
        this.id = id;
    }




}


