package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.psSchemaTableStatisticsIoId;

/**
 * X.psSchemaTableStatisticsIo generated by hbm2java
 */
public class X.psSchemaTableStatisticsIo  implements java.io.Serializable {


     private X.psSchemaTableStatisticsIoId id;

    public X.psSchemaTableStatisticsIo() {
    }

    public X.psSchemaTableStatisticsIo(X.psSchemaTableStatisticsIoId id) {
       this.id = id;
    }
   
    public X.psSchemaTableStatisticsIoId getId() {
        return this.id;
    }
    
    public void setId(X.psSchemaTableStatisticsIoId id) {
        this.id = id;
    }




}


