package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.schemaTableLockWaitsId;

/**
 * X.schemaTableLockWaits generated by hbm2java
 */
public class X.schemaTableLockWaits  implements java.io.Serializable {


     private X.schemaTableLockWaitsId id;

    public X.schemaTableLockWaits() {
    }

    public X.schemaTableLockWaits(X.schemaTableLockWaitsId id) {
       this.id = id;
    }
   
    public X.schemaTableLockWaitsId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTableLockWaitsId id) {
        this.id = id;
    }




}


