package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.schemaTableStatisticsId;

/**
 * X.schemaTableStatistics generated by hbm2java
 */
public class X.schemaTableStatistics  implements java.io.Serializable {


     private X.schemaTableStatisticsId id;

    public X.schemaTableStatistics() {
    }

    public X.schemaTableStatistics(X.schemaTableStatisticsId id) {
       this.id = id;
    }
   
    public X.schemaTableStatisticsId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTableStatisticsId id) {
        this.id = id;
    }




}


