package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.schemaFlattenedKeysId;

/**
 * X.schemaFlattenedKeys generated by hbm2java
 */
public class X.schemaFlattenedKeys  implements java.io.Serializable {


     private X.schemaFlattenedKeysId id;

    public X.schemaFlattenedKeys() {
    }

    public X.schemaFlattenedKeys(X.schemaFlattenedKeysId id) {
       this.id = id;
    }
   
    public X.schemaFlattenedKeysId getId() {
        return this.id;
    }
    
    public void setId(X.schemaFlattenedKeysId id) {
        this.id = id;
    }




}


