package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.schemaTableStatisticsWithBufferId;

/**
 * X.schemaTableStatisticsWithBuffer generated by hbm2java
 */
public class X.schemaTableStatisticsWithBuffer  implements java.io.Serializable {


     private X.schemaTableStatisticsWithBufferId id;

    public X.schemaTableStatisticsWithBuffer() {
    }

    public X.schemaTableStatisticsWithBuffer(X.schemaTableStatisticsWithBufferId id) {
       this.id = id;
    }
   
    public X.schemaTableStatisticsWithBufferId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTableStatisticsWithBufferId id) {
        this.id = id;
    }




}


