package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.schemaTablesWithFullTableScansId;

/**
 * X.schemaTablesWithFullTableScans generated by hbm2java
 */
public class X.schemaTablesWithFullTableScans  implements java.io.Serializable {


     private X.schemaTablesWithFullTableScansId id;

    public X.schemaTablesWithFullTableScans() {
    }

    public X.schemaTablesWithFullTableScans(X.schemaTablesWithFullTableScansId id) {
       this.id = id;
    }
   
    public X.schemaTablesWithFullTableScansId getId() {
        return this.id;
    }
    
    public void setId(X.schemaTablesWithFullTableScansId id) {
        this.id = id;
    }




}


