package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.schemaIndexStatisticsId;

/**
 * X.schemaIndexStatistics generated by hbm2java
 */
public class X.schemaIndexStatistics  implements java.io.Serializable {


     private X.schemaIndexStatisticsId id;

    public X.schemaIndexStatistics() {
    }

    public X.schemaIndexStatistics(X.schemaIndexStatisticsId id) {
       this.id = id;
    }
   
    public X.schemaIndexStatisticsId getId() {
        return this.id;
    }
    
    public void setId(X.schemaIndexStatisticsId id) {
        this.id = id;
    }




}


