package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.sessionId;

/**
 * X.session generated by hbm2java
 */
public class X.session  implements java.io.Serializable {


     private X.sessionId id;

    public X.session() {
    }

    public X.session(X.sessionId id) {
       this.id = id;
    }
   
    public X.sessionId getId() {
        return this.id;
    }
    
    public void setId(X.sessionId id) {
        this.id = id;
    }




}


