package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.statementsWithTempTablesId;

/**
 * X.statementsWithTempTables generated by hbm2java
 */
public class X.statementsWithTempTables  implements java.io.Serializable {


     private X.statementsWithTempTablesId id;

    public X.statementsWithTempTables() {
    }

    public X.statementsWithTempTables(X.statementsWithTempTablesId id) {
       this.id = id;
    }
   
    public X.statementsWithTempTablesId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithTempTablesId id) {
        this.id = id;
    }




}


