package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.statementsWithFullTableScansId;

/**
 * X.statementsWithFullTableScans generated by hbm2java
 */
public class X.statementsWithFullTableScans  implements java.io.Serializable {


     private X.statementsWithFullTableScansId id;

    public X.statementsWithFullTableScans() {
    }

    public X.statementsWithFullTableScans(X.statementsWithFullTableScansId id) {
       this.id = id;
    }
   
    public X.statementsWithFullTableScansId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithFullTableScansId id) {
        this.id = id;
    }




}


