package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.statementAnalysisId;

/**
 * X.statementAnalysis generated by hbm2java
 */
public class X.statementAnalysis  implements java.io.Serializable {


     private X.statementAnalysisId id;

    public X.statementAnalysis() {
    }

    public X.statementAnalysis(X.statementAnalysisId id) {
       this.id = id;
    }
   
    public X.statementAnalysisId getId() {
        return this.id;
    }
    
    public void setId(X.statementAnalysisId id) {
        this.id = id;
    }




}


