package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.statementsWithSortingId;

/**
 * X.statementsWithSorting generated by hbm2java
 */
public class X.statementsWithSorting  implements java.io.Serializable {


     private X.statementsWithSortingId id;

    public X.statementsWithSorting() {
    }

    public X.statementsWithSorting(X.statementsWithSortingId id) {
       this.id = id;
    }
   
    public X.statementsWithSortingId getId() {
        return this.id;
    }
    
    public void setId(X.statementsWithSortingId id) {
        this.id = id;
    }




}


