package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.userSummaryByStatementLatencyId;

/**
 * X.userSummaryByStatementLatency generated by hbm2java
 */
public class X.userSummaryByStatementLatency  implements java.io.Serializable {


     private X.userSummaryByStatementLatencyId id;

    public X.userSummaryByStatementLatency() {
    }

    public X.userSummaryByStatementLatency(X.userSummaryByStatementLatencyId id) {
       this.id = id;
    }
   
    public X.userSummaryByStatementLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByStatementLatencyId id) {
        this.id = id;
    }




}


