package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.userSummaryByFileIoTypeId;

/**
 * X.userSummaryByFileIoType generated by hbm2java
 */
public class X.userSummaryByFileIoType  implements java.io.Serializable {


     private X.userSummaryByFileIoTypeId id;

    public X.userSummaryByFileIoType() {
    }

    public X.userSummaryByFileIoType(X.userSummaryByFileIoTypeId id) {
       this.id = id;
    }
   
    public X.userSummaryByFileIoTypeId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByFileIoTypeId id) {
        this.id = id;
    }




}


