package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.userSummaryId;

/**
 * X.userSummary generated by hbm2java
 */
public class X.userSummary  implements java.io.Serializable {


     private X.userSummaryId id;

    public X.userSummary() {
    }

    public X.userSummary(X.userSummaryId id) {
       this.id = id;
    }
   
    public X.userSummaryId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryId id) {
        this.id = id;
    }




}


