package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.userSummaryByFileIoId;

/**
 * X.userSummaryByFileIo generated by hbm2java
 */
public class X.userSummaryByFileIo  implements java.io.Serializable {


     private X.userSummaryByFileIoId id;

    public X.userSummaryByFileIo() {
    }

    public X.userSummaryByFileIo(X.userSummaryByFileIoId id) {
       this.id = id;
    }
   
    public X.userSummaryByFileIoId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByFileIoId id) {
        this.id = id;
    }




}


