package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.userSummaryByStatementTypeId;

/**
 * X.userSummaryByStatementType generated by hbm2java
 */
public class X.userSummaryByStatementType  implements java.io.Serializable {


     private X.userSummaryByStatementTypeId id;

    public X.userSummaryByStatementType() {
    }

    public X.userSummaryByStatementType(X.userSummaryByStatementTypeId id) {
       this.id = id;
    }
   
    public X.userSummaryByStatementTypeId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByStatementTypeId id) {
        this.id = id;
    }




}


