package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.userSummaryByStagesId;

/**
 * X.userSummaryByStages generated by hbm2java
 */
public class X.userSummaryByStages  implements java.io.Serializable {


     private X.userSummaryByStagesId id;

    public X.userSummaryByStages() {
    }

    public X.userSummaryByStages(X.userSummaryByStagesId id) {
       this.id = id;
    }
   
    public X.userSummaryByStagesId getId() {
        return this.id;
    }
    
    public void setId(X.userSummaryByStagesId id) {
        this.id = id;
    }




}


