package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.waitClassesGlobalByAvgLatencyId;

/**
 * X.waitClassesGlobalByAvgLatency generated by hbm2java
 */
public class X.waitClassesGlobalByAvgLatency  implements java.io.Serializable {


     private X.waitClassesGlobalByAvgLatencyId id;

    public X.waitClassesGlobalByAvgLatency() {
    }

    public X.waitClassesGlobalByAvgLatency(X.waitClassesGlobalByAvgLatencyId id) {
       this.id = id;
    }
   
    public X.waitClassesGlobalByAvgLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitClassesGlobalByAvgLatencyId id) {
        this.id = id;
    }




}


