package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.waitClassesGlobalByLatencyId;

/**
 * X.waitClassesGlobalByLatency generated by hbm2java
 */
public class X.waitClassesGlobalByLatency  implements java.io.Serializable {


     private X.waitClassesGlobalByLatencyId id;

    public X.waitClassesGlobalByLatency() {
    }

    public X.waitClassesGlobalByLatency(X.waitClassesGlobalByLatencyId id) {
       this.id = id;
    }
   
    public X.waitClassesGlobalByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitClassesGlobalByLatencyId id) {
        this.id = id;
    }




}


