package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.waitsByUserByLatencyId;

/**
 * X.waitsByUserByLatency generated by hbm2java
 */
public class X.waitsByUserByLatency  implements java.io.Serializable {


     private X.waitsByUserByLatencyId id;

    public X.waitsByUserByLatency() {
    }

    public X.waitsByUserByLatency(X.waitsByUserByLatencyId id) {
       this.id = id;
    }
   
    public X.waitsByUserByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitsByUserByLatencyId id) {
        this.id = id;
    }




}


