package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.waitsGlobalByLatencyId;

/**
 * X.waitsGlobalByLatency generated by hbm2java
 */
public class X.waitsGlobalByLatency  implements java.io.Serializable {


     private X.waitsGlobalByLatencyId id;

    public X.waitsGlobalByLatency() {
    }

    public X.waitsGlobalByLatency(X.waitsGlobalByLatencyId id) {
       this.id = id;
    }
   
    public X.waitsGlobalByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitsGlobalByLatencyId id) {
        this.id = id;
    }




}


