package com.demo.model;
// Generated Mar 3, 2021, 12:02:21 PM by Hibernate Tools 5.4.27.Final


import com.demo.model.X.waitsByHostByLatencyId;

/**
 * X.waitsByHostByLatency generated by hbm2java
 */
public class X.waitsByHostByLatency  implements java.io.Serializable {


     private X.waitsByHostByLatencyId id;

    public X.waitsByHostByLatency() {
    }

    public X.waitsByHostByLatency(X.waitsByHostByLatencyId id) {
       this.id = id;
    }
   
    public X.waitsByHostByLatencyId getId() {
        return this.id;
    }
    
    public void setId(X.waitsByHostByLatencyId id) {
        this.id = id;
    }




}


